### ISSUE TITLE
Country of created Account is not respected in "welcome" e-mail

### ISSUE THREAD

**Issue by holtkamp** [mollie/reseller-api#11]
When [creating an Account](https://www.mollie.com/nl/support/post/documentatie-reseller-api/#ref-account-create) for a Dutch company (```country: NL```), an e-mail is dispatched to the indicated e-mail address in the Dutch language: great!

The e-mail invites the recipient to activate the newly created Account, however, the activation link 

- https://mollie.com/dashboard/login/activate/$partnerId/$randomCode?lang=en

points to an **English** version of the terms of Mollie to accept: 

https://www.mollie.com/en/terms/sign?redirect_url=https%3A%2F%2Fwww.mollie.com%2Fdashboard%2F

I would expect the terms to be presented in the appropriate language (Dutch for companies in The Netherlands). If presented in English, I expect a lot of our resellers to become frightened / confused and NOT accept the terms...

**Notes**
Changing the ```?lang=en``` GET parameter in the activation URL to ```?lang=nl```does not have any effect. 
Changing ```/en/``` in the terms URL to ```/nl``` DOES have effect:

https://www.mollie.com/nl/terms/sign?redirect_url=https%3A%2F%2Fwww.mollie.com%2Fdashboard%2F

Also note the layout of the activation button in the e-mail seems incorrect, when comparing it to former e-mails (that pointed to a different URL as well, I guess you guys are migrating to the new dashboard)

Old e-mail layout (proper button and hyperlink formatting)
---
<img width="517" alt="screen shot 2017-02-14 at 15 17 59" src="https://cloud.githubusercontent.com/assets/776405/22932617/d105ba7a-f2c8-11e6-903a-5f3d0d89cbcf.png">

New e-mail layout (strange button and hyperlink formatting)
---
![screen shot 2017-02-14 at 15 17 38](https://cloud.githubusercontent.com/assets/776405/22932641/f1d37e0e-f2c8-11e6-8fa6-455c1cb4cd9a.png)

**Comment by willemstuursma** [comment]
Hi @holtkamp. We'll be resolving the language issue somewhere next week.

When did you start getting the error in email layout?

**Comment by willemstuursma** [comment]
We've made some changes. Can you confirm that everything is working correctly now?

**Comment by holtkamp** [comment]
>Can you confirm that everything is working correctly now?

Well, it is a bit difficult to test 😄 , we need to create Reseller accounts for 'real companies', with real data for this to test. In general we do not have access to the mail-accounts of these companies. So for the time being I can not answer this question...

**Comment by willemstuursma** [comment]
OK, I'm going to rely on our internal testing then! Let me know if you figure out something is still not working as expected.

**Comment by holtkamp** [comment]
@willemstuursma due to the change in style of Mollie, we needed to update the screenshots in our documentation. I just created a new partner account to test. The locale seems respected, but the formatting is still "crazy" / incorrect: the button with the activation link is rendered incorrectly, at least in GMail and Amazon WorkMail web clients.

GMail:

<img width="232" alt="screen shot 2017-04-24 at 10 40 19" src="https://cloud.githubusercontent.com/assets/776405/25329070/9467ef6e-28da-11e7-879f-899469176c40.png">


Amazon WorkMail:

<img width="297" alt="screen shot 2017-04-24 at 10 40 40" src="https://cloud.githubusercontent.com/assets/776405/25329068/90ee428e-28da-11e7-93e3-d3031373e8c8.png">


The Button does contain the  proper URL though, only the formatting breaks.. Maybe this deserves a separate issue?

**Comment by willemstuursma** [comment]
Hi @holtkamp. Thanks for bringing this up, we're going to look into it.

**Comment by holtkamp** [comment]
@willemstuursma did you guys have a look? Any ETA on this? We are planning on creating Mollie partner IDs for a big amount of our customers...

**Comment by willemstuursma** [comment]
@holtkamp We're trying to get it fixed this week, sorry.

**Comment by holtkamp** [comment]
@willemstuursma ok, great, standing by and waiting for a heads-up 😄

**Comment by holtkamp** [comment]
@willemstuursma any news on this? ETA?

**Comment by willemstuursma** [comment]
@holtkamp I just got word this has been resolved by our team, I expect it will be deployed later today.
