### ISSUE TITLE
sandbox mode

### ISSUE THREAD

**Issue by sweebee** [mollie/reseller-api#14]
Is it possible to use this api in some kind of sandbox mode?

I'm implementing that my system creates automatically a new account and a profile. But I need to test it without actually creating something.

**Comment by JorikMollie** [comment]
Our reseller API has no sandbox. So you can't test without creating an account.

If you mail a list of accounts that were created during testing to info@mollie.com we'll close the accounts for you.

**Comment by sweebee** [comment]
Looks like testmode is implemented
