### ISSUE TITLE
Function create_function() is deprecated on PHP 7.2

### ISSUE THREAD

**Issue by PaulKruijt** [mollie/reseller-api#15]
On PHP 7.2 i get a deprecated exception on "create_function":

```
public function __construct ($partner_id, $profile_key, $app_secret)
{
    // Set persistent parameters
    $this->setPersistentParam('partner_id',  $partner_id);
    $this->setPersistentParam('profile_key', $profile_key);
 
    // Make a private secret callable
    $this->_callableSecret = create_function('', 'return '.var_export($app_secret, TRUE).';');
}
```

**Comment by willemstuursma** [comment]
Thanks for bringing this up.

@mvdpanne could you have a look at this? 

You can up the minimum PHP to 5.6, check the `.travis.yml` from the mollie/mollie-api-php for some more tips. Any brush ups are appreciated.

**Comment by TomasVotruba** [comment]
If you ever need to upgrade more  `create_function` cases, [Rector does it pretty well](https://github.com/rectorphp/rector/commit/3376254f7742abab3fde0a865ae4de8a420e964f).
