### ISSUE TITLE
Disconnect Account Method

### ISSUE THREAD

**Issue by patbro** [mollie/reseller-api#17]
It is not possible to disconnect a partner account a using the website of Mollie or by phone. Hence why, I downloaded the beautiful PHP Reseller API. 

Unfortunately, in the Reseller API there is no "[disconnect account](https://help.mollie.com/hc/en-us/articles/214016745-Waar-kan-ik-de-API-documentatie-voor-resellers-vinden-#ref-disconnect-account)" method. It is very easy to implement this into the Reseller API and will make life for a lot of developers a whole lot easier.

**Comment by willemstuursma** [comment]
Hi @pvanbroeckhuijsen! We'll add it in the next few weeks but if you are in a rush, you can always create a pul request.
