### ISSUE TITLE
Installation of 1.7.x fails

### ISSUE THREAD

**Issue by holtkamp** [mollie/reseller-api#2]
When using the following, most simplistic ```composer.json```:

```json
{
  "require": {
    "mollie/reseller-api": "^1.7"
  }
}
```

Installation fails with:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package mollie/reseller-api ^1.7 exists as mollie/reseller-api[1.5.0, 1.6.0, dev-master] but these are rejected by your constraint.
```

When using ```^1.6``` it succeeds => 1.6 is installed. 

I think this is caused by the version number (1.6) in the ```composer.json``` file in the releases, for example:

- https://github.com/mollie/reseller-api/blob/v1.7.0/composer.json#L3
- https://github.com/mollie/reseller-api/blob/v1.7.1/composer.json#L3

Including this version number "statically" is actually discouraged...
https://getcomposer.org/doc/04-schema.md#version

I would suggest removing it, both in the master branch and the 1.7.x branches...

**Comment by holtkamp** [comment]
Same applies for https://github.com/mollie/reseller-api/blob/c09303ffd71e7ae229981b41d726ed4407449750/php/src/mollie/reseller.php#L32

**Comment by willemstuursma** [comment]
Thanks. This has been resolved and I've added a `composer validate` check to travis so it won't happen again.
