### ISSUE TITLE
Use of partner_id_customer outdated?

### ISSUE THREAD

**Issue by holtkamp** [mollie/reseller-api#3]
For some methods of the Reseller API, the documentation suggests one can use ```partner_id_customer``` as parameter instead of ```username``` and ```password```. 

For [example](https://www.mollie.com/beheer/reseller/documentatie#ref-bankaccounts):

![screen shot 2017-01-05 at 16 17 40](https://cloud.githubusercontent.com/assets/776405/21685614/8849395e-d362-11e6-9f38-7e9553f94598.png)

However, when looking at the function signature of [bankAccounts()](https://github.com/mollie/reseller-api/blob/c09303ffd71e7ae229981b41d726ed4407449750/php/src/mollie/reseller.php#L89) it seems this parameter is not accepted / used. 

When searching this repository for the ```partner_id_customer``` parameter, it only shows up in the ```availablePaymentMethodsByPartnerId()``` method. 

https://github.com/mollie/reseller-api/search?utf8=%E2%9C%93&q=partner_id_customer

Can someone clarify this? Is the documentation or the code in need for an update, or am I missing the point here 😄

**Comment by FaaPz** [comment]
Thank you for your PR! We've merged it, updated some tests and tagged a new version **v1.8.0**. 👍

**Comment by holtkamp** [comment]
Awesome! Thanks
