### ISSUE TITLE
Update bank account information using accountEdit()?

### ISSUE THREAD

**Issue by holtkamp** [mollie/reseller-api#5]
Is it possible to edit / update / add bank account information using ```accountEdit()``` **after** an (Mollie) Account was created using ```accountCreate()```?

I am asking because the (the bankaccount_* properties are not mentioned in the [documentation of that method](https://www.mollie.com/beheer/reseller/documentatie#ref-account-edit).

Since it is not possible to inspect the details of an Account, it is now unsure whether all information is added properly. This is reported in https://github.com/mollie/reseller-api/issues/6

**Comment by FaaPz** [comment]
Unfortunately it's not possible to change bank account information in any way after creating an Account. We'll be focusing on our [Mollie Connect](https://www.mollie.com/nl/docs/oauth/overview) APIs, so this feature won't be added either.
