### ISSUE TITLE
List accounts functionality

### ISSUE THREAD

**Issue by holtkamp** [mollie/reseller-api#6]
Is there any way to 'list' the Accounts that were created using ```accountCreate()```?

Currently it seems impossible to inspect whether all settings (like bank information) is created / assigned successfully. 

Also see https://github.com/mollie/reseller-api/issues/5

**Comment by FaaPz** [comment]
Hi @holtkamp, as of now it's not possible to retrieve a list of created Mollie Accounts via our Reseller API. We'll also be focusing on improving our [Mollie Connect](https://www.mollie.com/nl/docs/oauth/overview) APIs, so this feature won't be added either unfortunately.

**Comment by holtkamp** [comment]
@FaaPz ok thanks for the answer. I would like to suggest to change this sentence in the ```README``` though:

>Maar in de tussentijd wordt u geadviseerd deze Reseller API te gebruiken en krijgt u daar uiteraard volledige ondersteuning bij.

I would NOT advise anyone starting with using reseller functionality to use this Reseller API. Eventually one will need the (more advanced) functionality as only provided by Mollie Connect / the Mollie API, so better start with it directly... just my 2 cents 😄
