### ISSUE TITLE
Parameter bankaccount_location seems not mandatory for accountCreate()

### ISSUE THREAD

**Issue by holtkamp** [mollie/reseller-api#7]
The [documentation of accountCreate()](https://www.mollie.com/beheer/reseller/documentatie#ref-account-create) suggests that when providing ```bankaccount_iban``` all other ```bankaccount_*``` properties should also be provided, which includes ```bankaccount_location```. 

But since, we do not always have this information I tried to create an Account **without** ```bankaccount_location```, which seems to work properly (both in testmodus and non-testmodus).

Can someone shed a light on this? (Is it mandatory, or not 😄 )

**Comment by willemstuursma** [comment]
Sorry, this parameter is only there for legacy reasons. We don't need the bank's location anymore.
