### ISSUE TITLE
How to create/enable a PaymentMethod for a WebSite Profile?

### ISSUE THREAD

**Issue by holtkamp** [mollie/reseller-api#8]
After creating a WebSite Profile using ```accountCreate()``` [as documented here](https://www.mollie.com/nl/support/post/documentatie-reseller-api#ref-profile-create) we would like to enable a certain PaymentMethod (iDEAL) for it. 

It seems this is currently not possible using the API?

**Comment by FaaPz** [comment]
@holtkamp Sorry, but it's not possible via our API. I think it is something we can take into consideration as improvement for one of our [Mollie Connect](https://www.mollie.com/nl/docs/oauth/overview) APIs.
