### ISSUE TITLE
List profiles function only returns active profiles, why?

### ISSUE THREAD

**Issue by holtkamp** [mollie/reseller-api#9]
The documentation states that the ```profiles()``` function **only** returns active profiles. 

When looking at the response:

```xml
<?xml version="1.0"?>
<response>
  <items>
    <profile>
      <name>Snoep.nl</name>
      <hash>9C696E36</hash>
      <website>http://snoep.nl/</website>
      <sector>6</sector>
      <category>5399</category>
      <verified>true</verified>
      <phone>0201234567</phone>
      <email>info@snoep.nl</email>
      <api_keys>
        <test>xxx</test>
        <live>xxx</live>
      </api_keys>
    </profile>
  </items>
</response> 
```

The ```verified``` field indicates whether the profile is active or not. Why this limitation to only return the active ones? After creating a profile, I would like to be able to verify it has been created successfully and awaiting verification with for all profiles with ```<verified>false</verified>```. 

I know the ```createProfile()``` method returns a result code to determine the success. But to be ably to monitor the status periodically, listing all profiles (both activated and non-activated) would be nice.

**Comment by willemstuursma** [comment]
Thanks for bringing this to our attention. I'll see if we can change this API method. I've updated your issue to remove the API keys.

**Comment by holtkamp** [comment]
>I've updated your issue to remove the API keys.

Ah, ok, it they were from the example provided in [Mollies profiles() documentation](https://www.mollie.com/beheer/reseller/documentatie#ref-profiles), thought these were dummy keys. But these were real-life keys injected automagically? 😨 Hope not... Assume not... 😄

**Comment by willemstuursma** [comment]
They were indeed dummy keys.

We've updated the API to return all profiles, both verified and unverified. Thanks for reporting this.

**Comment by holtkamp** [comment]
@willemstuursma ah, nice, thanks for this quick action! 

~~You got an ETA on when this change will be deployed to production? Currently the behaviour seems not changed, no problem, just verifying~~ 😄 

=> it's working! Also non-verified profiles are returned 👍
